### ISSUE TITLE
travis fails due to sdkman

### ISSUE THREAD

**Issue by julian1** [aodn/aatams#359] opened 2016-12-08 22:44 UTC
I'm looking

**Comment by julian1** [comment] 2017-02-28 00:07
one hour is not enough time to download all the dependencies. The maven/grails cache that persisted across builds was lost at some point  - and it's not built successfully since then.

**Comment by jonescc** [comment] 2017-07-04 22:38
Fixed by https://github.com/aodn/aatams/pull/394

**Comment by xhoenner** [comment] 2017-09-07 00:12
Re-opening this issue as none of the PRs can be merged due to an error in the Travis build. See https://travis-ci.org/aodn/aatams/builds/272356656?utm_source=github_status&utm_medium=notification for instance.

 Could this be a similar issue to https://github.com/aodn/aatams/pull/394 @bhasin85 @jonescc ? Let me know if you think this can't be fixed easily and thus needs to be considered for the next iteration.

**Comment by bhasin85** [comment] 2017-09-07 06:35
@xhoenner The issue is with sdkman installation and not with the maven dependencies. I would suggest you to open a new issue. 

_**Build Error**_
> The command "source "/home/travis/.sdkman/bin/sdkman-init.sh"" failed and exited with 1 during .

**Comment by xhoenner** [comment] 2017-09-07 22:17
Thanks @bhasin85, closing this issue and opened a new one --> https://github.com/aodn/aatams/issues/404

**Closed by xhoenner** 2017-09-07 22:17 UTC
Labels: bug, medium priority

**Comment by jonescc** [comment] 2017-09-07 23:58
Another instance of https://en.wikipedia.org/wiki/Software_rot - not the same as the one above.
